-- AlterTable
ALTER TABLE `evento` ADD COLUMN `status` ENUM('PENDENTE', 'APROVADO', 'REJEITADO') NOT NULL DEFAULT 'PENDENTE';

-- AlterTable
ALTER TABLE `pontoturistico` ADD COLUMN `status` ENUM('PENDENTE', 'APROVADO', 'REJEITADO') NOT NULL DEFAULT 'PENDENTE';
